App:
  AppDebug: true
  Port: ":8080"
  AllowCrossDomain: true
  LogPath: "/Users/y/code/cxsd/ginShoppingMall/log"
  LogType: "file"
  LogInfoName: "app.log"
  LogErrorName: "app-error.log"
  JwtTokenSignKey: "lpWY3c9OegAdFh7y"   #设置token生成时加密的签名
  JwtTokenOnlineUsers: 10         #一个账号密码允许最大获取几个有效的token，当超过这个值，第一次获取的token的账号、密码就会失效
  JwtTokenCreatedExpireAt: 28800      #创建时token默认有效秒数（token生成时间加上该时间秒数，算做有效期）,3600*8=28800 等于8小时
  JwtTokenRefreshExpireAt: 36000

Admin:
  AppDebug: true
  Port: ":9090"
  AllowCrossDomain: true
  LogPath: "/Users/y/code/cxsd/ginShoppingMall/log"
  LogType: "file"
  LogInfoName: "admin.log"
  LogErrorName: "admin-error.log"
  JwtTokenSignKey: "lpWY3c9OegAdFh7y"   #设置token生成时加密的签名
  JwtTokenOnlineUsers: 10         #一个账号密码允许最大获取几个有效的token，当超过这个值，第一次获取的token的账号、密码就会失效
  JwtTokenCreatedExpireAt: 28800      #创建时token默认有效秒数（token生成时间加上该时间秒数，算做有效期）,3600*8=28800 等于8小时
  JwtTokenRefreshExpireAt: 36000

Redis:
  Host: "127.0.0.1"
  Port: 6379
  Auth: ""
  MaxIdle: 10
  MaxActive: 1000
  IdleTimeout: 60
  IndexDb: 0
  ConnFailRetryTimes: 3    #从连接池获取连接失败，最大重试次数
  ReConnectInterval: 1     # 从连接池获取连接失败，每次重试之间间隔的秒数

#
#Token:
#  JwtTokenSignKey: "lpWY3c9OegAdFh7y"   #设置token生成时加密的签名
#  JwtTokenOnlineUsers: 10         #一个账号密码允许最大获取几个有效的token，当超过这个值，第一次获取的token的账号、密码就会失效
#  JwtTokenCreatedExpireAt: 28800      #创建时token默认有效秒数（token生成时间加上该时间秒数，算做有效期）,3600*8=28800 等于8小时
#  JwtTokenRefreshExpireAt: 36000      #对于过期的token，支持从相关接口刷新获取新的token，默认有效期为10个小时，3600*10=36000 等于10小时
##  BindContextKeyName: "userToken"     #用户在 header 头部提交的token绑定到上下文时的键名，方便直接从上下文(gin.context)直接获取每个用户的id等信息
