// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Cheney",
            "url": "http://adaday.cn",
            "email": "YuanShengSH@outlook.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/captcha/pic": {
            "get": {
                "description": "获取图片验证码",
                "tags": [
                    "API USER 用户"
                ],
                "summary": "获取图片验证码",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "手机号",
                        "name": "mobile",
                        "in": "query",
                        "required": true
                    }
                ]
            }
        },
        "/api/captcha/sms": {
            "post": {
                "description": "获取短信验证码",
                "tags": [
                    "API USER 用户"
                ],
                "summary": "获取短信验证码",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "手机号",
                        "name": "mobile",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "图形验证码",
                        "name": "captcha",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/api/product": {
            "get": {
                "description": "商品信息",
                "tags": [
                    "API PRODUCT 商品"
                ],
                "summary": "商品信息"
            }
        },
        "/api/product/spec": {
            "get": {
                "description": "商品信息",
                "tags": [
                    "API PRODUCT 商品"
                ],
                "summary": "商品信息"
            }
        },
        "/api/user": {
            "get": {
                "description": "获取用户信息",
                "tags": [
                    "API USER 用户"
                ],
                "summary": "获取用户信息"
            },
            "put": {
                "description": "更新用户信息",
                "tags": [
                    "API USER 用户"
                ],
                "summary": "更新用户信息"
            }
        },
        "/api/user/login": {
            "post": {
                "description": "用户登录",
                "tags": [
                    "API USER 用户"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginOutput"
                        }
                    }
                }
            }
        },
        "/api/user/register": {
            "post": {
                "description": "用户注册",
                "tags": [
                    "API USER 用户"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "手机号",
                        "name": "mobile",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "手机验证码",
                        "name": "captcha",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, \"data\": [...]}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.UserLoginOutput": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "access_token",
                    "type": "string"
                },
                "expires_at": {
                    "description": "expires_in",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        ":8080",
	BasePath:    "/api",
	Schemes:     []string{},
	Title:       "ginShoppingMall API",
	Description: "接口描述",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
